In [6]:
import numpy as np
from numpy import array
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.models import load_model
import pandas as pd

In [7]:
df = pd.read_csv('../Data.csv')
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df = df.reset_index()['close']

In [46]:
df1 =pd.DataFrame(df).to_numpy()

In [56]:
df1[-1][0]


np.float64(0.7789988252681044)

In [42]:
df1 = df.values

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [41]:
out=df[-1, 0]  
print(out)

0.7789988252681044


In [16]:
df

array([[0.02064876],
       [0.0295123 ],
       [0.03521164],
       ...,
       [0.75357914],
       [0.75752018],
       [0.77899883]])

In [8]:
scaler=MinMaxScaler (feature_range=(0,1))
df=scaler.fit_transform(np.array(df).reshape(-1,1))
    

In [21]:
df1 = df[-62:-2]
df1

array([[0.85004358],
       [0.86228732],
       [0.88891584],
       [0.87186707],
       [0.85969533],
       [0.85558377],
       [0.83585206],
       [0.80431619],
       [0.80796544],
       [0.80313767],
       [0.81109174],
       [0.79718443],
       [0.8278563 ],
       [0.85271136],
       [0.85338967],
       [0.86318542],
       [0.84974421],
       [0.86282921],
       [0.87411042],
       [0.88813142],
       [0.89409224],
       [0.90761681],
       [0.91020501],
       [0.90868165],
       [0.91041722],
       [0.9136951 ],
       [0.90598355],
       [0.91375573],
       [0.9132631 ],
       [0.89380803],
       [0.88157945],
       [0.86776687],
       [0.83496912],
       [0.84200993],
       [0.84128235],
       [0.84337792],
       [0.84450339],
       [0.83783016],
       [0.83921331],
       [0.84727727],
       [0.87289022],
       [0.86443215],
       [0.82784494],
       [0.83665542],
       [0.82832999],
       [0.81429005],
       [0.79552844],
       [0.753

In [22]:
df=scaler.fit_transform(np.array(df).reshape(-1,1))
x_input = df[-62:-2].reshape(1,-1)
len(x_input)

1

In [23]:
x_input[0]

array([0.85004358, 0.86228732, 0.88891584, 0.87186707, 0.85969533,
       0.85558377, 0.83585206, 0.80431619, 0.80796544, 0.80313767,
       0.81109174, 0.79718443, 0.8278563 , 0.85271136, 0.85338967,
       0.86318542, 0.84974421, 0.86282921, 0.87411042, 0.88813142,
       0.89409224, 0.90761681, 0.91020501, 0.90868165, 0.91041722,
       0.9136951 , 0.90598355, 0.91375573, 0.9132631 , 0.89380803,
       0.88157945, 0.86776687, 0.83496912, 0.84200993, 0.84128235,
       0.84337792, 0.84450339, 0.83783016, 0.83921331, 0.84727727,
       0.87289022, 0.86443215, 0.82784494, 0.83665542, 0.82832999,
       0.81429005, 0.79552844, 0.75342378, 0.77143128, 0.77674789,
       0.78912805, 0.78652848, 0.79628633, 0.76780477, 0.76502709,
       0.77575126, 0.75914207, 0.72822388, 0.72926977, 0.75357914])

In [24]:
temp_input = list(x_input)
temp_input = temp_input[0].tolist()

In [25]:
len(temp_input)

60

In [26]:
def predict(df, time_step):
    scaler=MinMaxScaler (feature_range=(0,1))
    df=scaler.fit_transform(np.array(df).reshape(-1,1))
    x_input = df[-62:-2].reshape(1,-1)
    temp_input = list(x_input)
    temp_input = temp_input[0].tolist()
    
    model = load_model('lstm_model.h5')
    
    lst_output=[]
    n_steps=time_step
    i=0
    while(i<1):

        if(len(temp_input)>time_step):
            #print(temp_input)
            x_input=np.array(temp_input[1:])
            print("{} day input {}".format(i,x_input))
            x_input=x_input.reshape(1,-1)
            x_input = x_input.reshape((1, n_steps, 1))
            #print(x_input)
            yhat = model.predict(x_input, verbose=0)
            print("{} day output {}".format(i,yhat))
            temp_input.extend(yhat[0].tolist())
            temp_input=temp_input[1:]
            #print(temp_input)
            lst_output.extend(yhat.tolist())
            i=i+1
        else:
            x_input = x_input.reshape((1, n_steps,1))
            yhat = model.predict(x_input, verbose=0)
            print(yhat[0])
            temp_input.extend(yhat[0].tolist())
            print(len(temp_input))
            lst_output.extend(yhat.tolist())
            i=i+1
    return yhat

In [29]:
out = predict(df,60)
out

[0.76343954]
61


[[0.7634395360946655]]

In [28]:
actual_value = df[-1]
actual_value

array([0.77899883])

In [30]:
error = (out-actual_value)/actual_value
error

array([[-0.01997344]])